/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package controller

import (
	"fmt"
	"regexp"
	"strings"

	dbv1 "github.com/personal/cluster/services/operators/db/api/v1"
)

// 标识符/类型白名单校验，防止 CR 内容注入 SQL。
var (
	identifierRe = regexp.MustCompile(`^[A-Za-z][A-Za-z0-9_]{0,63}$`)
	dataTypeRe   = regexp.MustCompile(`^[A-Za-z][A-Za-z0-9_ (),]*$`)
	charsetRe    = regexp.MustCompile(`^[A-Za-z0-9_]+$`)
)

// sqlEscaper 转义 SQL 单引号字符串中的反斜杠与单引号。
var sqlEscaper = strings.NewReplacer(`\`, `\\`, `'`, `\'`)

func quoteIdent(name string) string { return "`" + name + "`" }

func validateIdentifier(field, name string) error {
	if !identifierRe.MatchString(name) {
		return fmt.Errorf("%s %q 不合法：须以字母开头，仅含字母/数字/下划线，长度 1~64", field, name)
	}
	return nil
}

// RenderInitSQL 把 CR 中声明的库表定义渲染为 MySQL 初始化脚本。
// 该脚本由 mysql 官方镜像在数据目录首次初始化时执行（/docker-entrypoint-initdb.d）。
func RenderInitSQL(databases []dbv1.InitDatabase) (string, error) {
	if len(databases) == 0 {
		return "", nil
	}
	var b strings.Builder
	b.WriteString("-- Generated by db-operator from Database CR. DO NOT EDIT.\n")
	b.WriteString("-- NOTE: 仅在 MySQL 数据目录首次初始化时自动执行；之后修改 CR 不会自动重放。\n")
	for _, d := range databases {
		if err := validateIdentifier("databases[].name", d.Name); err != nil {
			return "", err
		}
		charset := d.Charset
		if charset == "" {
			charset = "utf8mb4"
		}
		if !charsetRe.MatchString(charset) {
			return "", fmt.Errorf("databases[%q].charset %q 不合法：仅允许字母/数字/下划线", d.Name, charset)
		}
		fmt.Fprintf(&b, "\nCREATE DATABASE IF NOT EXISTS %s DEFAULT CHARACTER SET %s;\n", quoteIdent(d.Name), charset)
		fmt.Fprintf(&b, "USE %s;\n", quoteIdent(d.Name))
		for _, t := range d.Tables {
			sql, err := renderCreateTable(t, charset)
			if err != nil {
				return "", err
			}
			b.WriteString(sql)
		}
	}
	return b.String(), nil
}

func renderCreateTable(t dbv1.InitTable, charset string) (string, error) {
	if err := validateIdentifier("tables[].name", t.Name); err != nil {
		return "", err
	}
	if len(t.Columns) == 0 {
		return "", fmt.Errorf("databases[].tables[%q].columns 至少定义一列", t.Name)
	}
	pk := t.PrimaryKey
	var defs []string
	for _, c := range t.Columns {
		if err := validateIdentifier("tables[].columns[].name", c.Name); err != nil {
			return "", err
		}
		dt := strings.TrimSpace(c.Type)
		if !dataTypeRe.MatchString(dt) {
			return "", fmt.Errorf("tables[%q].columns[%q].type %q 不合法：仅允许字母/数字/下划线/空格/逗号/括号", t.Name, c.Name, c.Type)
		}
		def := quoteIdent(c.Name) + " " + dt
		if !c.Nullable {
			def += " NOT NULL"
		}
		if c.Comment != "" {
			def += fmt.Sprintf(" COMMENT '%s'", sqlEscaper.Replace(c.Comment))
		}
		if pk == "" && strings.Contains(strings.ToUpper(dt), "AUTO_INCREMENT") {
			return "", fmt.Errorf("table %q: 列 %q 为 AUTO_INCREMENT，须通过 primaryKey 指定主键", t.Name, c.Name)
		}
		defs = append(defs, def)
	}
	if pk != "" {
		found := false
		for _, c := range t.Columns {
			if c.Name == pk {
				found = true
				break
			}
		}
		if !found {
			return "", fmt.Errorf("table %q: primaryKey %q 未在 columns 中定义", t.Name, pk)
		}
	}
	var b strings.Builder
	fmt.Fprintf(&b, "CREATE TABLE IF NOT EXISTS %s (\n", quoteIdent(t.Name))
	b.WriteString("  " + strings.Join(defs, ",\n  "))
	if pk != "" {
		b.WriteString(",\n  PRIMARY KEY (" + quoteIdent(pk) + ")")
	}
	fmt.Fprintf(&b, "\n) ENGINE=InnoDB DEFAULT CHARSET=%s", charset)
	if t.Comment != "" {
		fmt.Fprintf(&b, " COMMENT='%s'", sqlEscaper.Replace(t.Comment))
	}
	b.WriteString(";\n")
	return b.String(), nil
}
